apiVersion: v1
kind: Secret
metadata:
  name: tickets-secret
  namespace: wendev
  labels:
    app.kubernetes.io/part-of: wendev-tickets
type: Opaque
stringData:
  PGUSER: "tickets"
  PGPASSWORD: "change-me-local-demo-password"

